version: "3"
services:
    nextjs:
        build:
            context: ./nextjs
            dockerfile: dev.Dockerfile
        container_name: nextjs
        restart: unless-stopped
        ports:
            - 3000:3000
        volumes:
            - ./nextjs/src:/app/src
            - ./nextjs/public:/app/public
        depends_on:
            - pocketbase
        networks:
            - internal
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.cal.rule=Host(`scrollmap.smkg.me`)"
            - "traefik.http.routers.cal.entrypoints=web"
            - "traefik.http.services.cal.loadbalancer.server.port=3000"
    pocketbase:
        build:
            context: ./pocketbase
            dockerfile: Dockerfile
        container_name: pocketbase
        restart: unless-stopped
        ports:
            - 8090:8090
        volumes:
            - ./pocketbase/data:/usr/local/bin/pb_data
        healthcheck: #optional (recommended) since v0.10.0
            test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8090/api/health || exit 1
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - internal
networks:
    internal:
        driver: bridge
